### ISSUE TITLE
booting openwrt on galileo gen2

### ISSUE THREAD

**Issue by kenyon22** [ECG-XMU/OpenWRT-Galileo-gen2#1]
Hello, 
I hope you'll be able to assist me. I successfully built the Galileo Gen2 OpenWRT image and followed the instructions to place the necessary files onto the SD-Card and edited the grub.conf. i tried this process multiple times and I'm just wondering what the problem could be. I wanted to know if this was succesfully tested using these instructions. Any help will be very appreciated, I am implemeting a "Smart Home Wireless Router" on galileo gen2 for my graduating thesis.

**Comment by lxzheng** [comment]
Could you please describe your issue in detail?

**Comment by kenyon22** [comment]
I downloaded the OpenWRT Galileo Gen2 Master from this repository, I built the image on my Ubuntu PC and it was a succesful built with just a warning at the end about the signing key not being configured but after some research i learned it was not an issue.

After building the image I followed the instruction in the Readme.md for Galileo gen 2；

/boot/grub/grub.conf

/bzImage

/grub.efi

/openwrt-x86-galileo-rootfs.cpio.gz

The 'bzImage' as stated in the instructions was found under '...linux-x86_galileo'

The 'openwrt-x86-galileo-rootfs.cpio.gz' also was built under '...bin/x86'

I located the grub.conf from the Intel Galileo SD-Card image along with the grub.efi and then I edited the grub.conf file to the following:

default 1 timeout 1

color white/blue white/cyan

title Clanton SVP kernel-SPI initrd-SPI IMR-On IO-APIC/HPET NoEMU kernel --spi root=/dev/ram0 console=ttyS1,115200n8 earlycon=uart8250,mmio32,$EARLY_CON_ADDR_REPLACE,115200n8 reboot=efi,warm apic=debug rw initrd --spi

title Clanton SVP kernel-MassStorage initrd-MassStorage image-full IMR-On IO-APIC/HPET NoEMU debug root (hd0,0) kernel /bzImage root=/dev/ram0 init=/init console=ttyS1,115200n8 earlycon=uart8250,mmio32,$EARLY_CON_ADDR_REPLACE,115200n8 reboot=efi,warm apic=debug rw LABEL=boot debugshell=5 rootimage= initrd /openwrt-x86-galileo-rootfs.cpio.gz

I placed the files on the SD-CARD and tried multiple times to get the image to load for over a month, o I wanted to find out how you tested the image, because I can successfully run and test the Intel SD-Card image and another Developer tools image  i've been working on, but not this OpenWRT image is not loading at all. Please verify the steps for me.

I am running an Intel Galileo Gen2 board and the firmware is 1.0.4, i tried to test it on 1.0.2 earlier, but it has the same results with the board not booting openwrt. Please run me through the steps with your tested configuration and if possible send me your working version to test.

Thank you.

**Comment by lxzheng** [comment]
You made some mistake in grub.conf. We have upload the grub to github.
Pls modify it according https://github.com/ECG-XMU/SDcard_grub

**Comment by kenyon22** [comment]
Thanks again for taking your time to help me, I tried testing my image with these updates and it's still not able to boot, actually the current image I have has some added packages not included in this repository such as "Openflow" but I have tried editing the grub.efi file many times with this format with the original packages in the repo it still failed. I will try to build the packages on this repository without any added packages then test it again, I'll give you feed back.

Thank you.

**Comment by kenyon22** [comment]
Hi,
I built the the original packages again, but i'm still not able to boot the image, I'm going to attach the SD-CARD files so you can check them and test them if possible and please send me your tested image.
[OpenWRT.zip](https://github.com/ECG-XMU/OpenWRT-Galileo-gen2/files/91342/OpenWRT.zip)

**Comment by kenyon22** [comment]
Hi,
I resolved the image boot error I was having, it was because I've been communicating with Galileo over Ethernet not using the FTDI connection, it's working perfectly now. Thank you very much for your help.

-kenyon
![screenshot from 2016-02-01 16 40 16](https://cloud.githubusercontent.com/assets/15712610/12712558/259427ba-c904-11e5-8540-f02d1f3fabfc.png)

**Comment by BobAfwata** [comment]
wonderful this is just what I needed
