### ISSUE TITLE
How to have a Root Volume on SD Card

### ISSUE THREAD

**Issue by UI-tedherman** [ECG-XMU/OpenWRT-Galileo-gen2#2]
The grub.conf has rootfs= (no root volume). How can the OpenWRT/Galileo access space on the SD card? Can it be an ext3 file if the ext3 fs is included in the kernel?

**Comment by lxzheng** [comment]
Pls just mount it. We used the fat32 format.  You can try ext3. It may be work.

**Comment by UI-tedherman** [comment]
I try to mount it, but I do not see what to mount. There is no /dev/mmc, and /sys/bus/sdio/devices is empty.  Also /sys/bus/mmc/devices is empty. Do I need to add kmod-mmc-over-gpio somehow to the minimal build to make it work, like it says https://wiki.openwrt.org/doc/howto/mmc_over_gpio ?
